<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>http://wiki.ros.org/msg, http://wiki.ros.org/srv, http://wiki.ros.org/actionlib</string>
	<key>fileTypes</key>
	<array>
		<string>msg</string>
		<string>srv</string>
		<string>action</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>ROS Message/Service/Action</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string-constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#field</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#separator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other-constant</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unknown.ros-msg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(\S.*)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.ros-msg</string>
		</dict>
		<key>field</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.ros-msg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.ros-msg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([\w/]+)(?:\[(\d+)?\])?\s+(\w+)\s*(?=$|#.*$)</string>
		</dict>
		<key>other-constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*([\w/]+)\s+(\w+)\s*=</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.ros-msg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.ros-msg</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.ros-msg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.language.boolean.ros-msg</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*(True|False)(?=\s*#|\s*$)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.float.ros-msg</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*(-?\d+\.\d+)(?=\s*#|\s*$)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.decimal.ros-msg</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*(-?\d+)(?=\s*#|\s*$)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.missing-value.ros-msg</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*(\n)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>separator</key>
		<dict>
			<key>comment</key>
			<string>Request/response separator for .srv, or goal/result/feedback separator for .action</string>
			<key>match</key>
			<string>^\s*---\s*$\n?</string>
			<key>name</key>
			<string>meta.separator.ros</string>
		</dict>
		<key>string-constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.ros-msg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.ros-msg</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.oted.ros-msg</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>"string constants are assigned the value of everything to the right of the equals sign, with leading and trailing whitespace removed. As such, you cannot leave a comment on a string constant definition."</string>
					<key>match</key>
					<string>^\s*(string)\s+(\w+)\s*=\s*(.*?)\s*$</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ros-msg</string>
	<key>uuid</key>
	<string>44C7FE44-3596-4717-8B4A-67251D63F6B2</string>
</dict>
</plist>
